dist: xenial
matrix:
  include:
    - language: ruby
      cache: bundler
      before_script: psql -c 'create database travis_ci_test;' -U postgres
      before_install:
        - gem update --system
        - gem install bundler
        - gem --version
        - bundler --version
      script: bundle exec rake
      services:
        - postgresql
        - redis-server
    - language: node_js
      node_js: 11
      cache: yarn
      script:
        - cd client/
        - yarn install
        - yarn test


