development:
  adapter: postgresql
  encoding: unicode
  database: photo_album_development
  pool: 5
  username: photo_album
  password: asdfasdf

test:
  adapter: postgresql
  encoding: unicode
  database: photo_album_test
  pool: 5
  username: photo_album
  password: asdfasdf

vagrant:
  adapter: postgresql
  encoding: unicode
  database: photo_album_vagrant
  pool: 5
  username: photo_album
  password: asdfasdf

production:
  adapter: postgresql
  encoding: unicode
  database: photo_album_production
  pool: 5
  username: photo_album
  password: asdfasdf
