shared: &shared
  host: <%= ENV.fetch("DATABASE_HOST") %>
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: photo_album
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>

development:
  <<: *shared
  database: photo_album_development

test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres
  adapter: postgresql

vagrant:
  <<: *shared
  database: photo_album_vagrant

production:
  <<: *shared
  database: photo_album_production
