development:
  adapter: postgresql
  encoding: unicode
  database: photo_album_development
  pool: 5
  username: photo_album
  password: asdfasdf

test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres
  adapter: postgresql

vagrant:
  adapter: postgresql
  encoding: unicode
  database: photo_album_vagrant
  pool: 5
  username: photo_album
  password: asdfasdf

production:
  adapter: postgresql
  encoding: unicode
  database: photo_album_production
  pool: 5
  username: photo_album
  password: asdfasdf
